### ISSUE TITLE
Ngrok for VS2019

### ISSUE THREAD

**Issue by TomBruns** [dprothero/NgrokExtensions#25] opened 2018-12-06 10:07 UTC
Add support for VS2019

**Comment by dprothero** [comment] 2019-02-28 21:04
@craigomatic @TomBruns Can you try out this release?
https://github.com/dprothero/NgrokExtensions/releases/tag/v0.9.12

**Comment by luebster** [comment] 2019-04-23 14:13
Confirmed works in Visual Studio Enterprise 2019 version 16.0.2

**Comment by tomasmcguinness** [comment] 2019-05-01 10:28
I'm using this release in VS2019, but my setup seems to be confusing it.

When running my project, I use http and https

![image](https://user-images.githubusercontent.com/302741/57013440-6fecc380-6c03-11e9-9817-aa71c2cf2c3e.png)

When I launch ngrok from the Tools menu, it results in this:

![image](https://user-images.githubusercontent.com/302741/57013518-cd811000-6c03-11e9-9616-ce7d3b51f823.png)

The forwarding is using the SSL port and a non-existent port. Any ideas how I can correct this on my side?

**Comment by luebster** [comment] 2019-05-01 16:43
I believe you have to uncheck Enable SSL in the project properties. I realize this will be a problem testing https.

![image](https://user-images.githubusercontent.com/394701/57029050-abd95600-6c0e-11e9-972a-c4e6d3290001.png)

**Comment by francesco-scullino** [comment] 2019-05-10 09:11
Hi,
I installed 0.9.12 version but seems to not work
![immagine](https://user-images.githubusercontent.com/1720798/57516033-34917980-7314-11e9-822d-b6a296e24b07.png)
![immagine](https://user-images.githubusercontent.com/1720798/57515950-0dd34300-7314-11e9-9292-b444c7b38898.png)
Any idea?

Thanks

**Comment by dprothero** [comment] 2019-09-14 17:54
VS 2019 support is in place, so I'm closing this issue.

The https issue is being tracked on issue #29

**Closed by dprothero** 2019-09-14 17:54 UTC
